### ISSUE TITLE
M1 Mac with Monterey, issue with driver for CH9102

### ISSUE THREAD

**Issue by ubidefeo** [m5stack/STAMP-C3#1]
When trying to use these boards with Mac OS Monterey on Macbook M1 Max,
the usb serial adapter is seen but uploading to the board (or doing any operations requiring writing to the device)
will fail with message `"A fatal error occurred: Failed to write to target RAM (result was 01070000: Operation timed out)"`

I have filed a detailed issue here https://github.com/m5stack/M5EPD/issues/47
The problem is the same

**Comment by kotelnikov** [comment]
@ubidefeo Hi, friend!!! Try this driver https://github.com/WCHSoftGroup/ch34xser_macos for my M1 PRO it works like a charm. But when installing carefully read readme, all steps important.

**Comment by TinyuZhao** [comment]
Sorry, we don't have a M1 chip for Mac to test, you can try this friend's method upstairs

**Comment by kotelnikov** [comment]
@ubidefeo Hello! Try the driver from this repo https://github.com/WCHSoftGroup/ch34xser_macos . It works on my M1 Pro without any issues.

**Comment by BadFlamingo666** [comment]
Hi! Trying the example in the readme gives me the following error:
fatal error: Freenove_WS2812_Lib_for_ESP32.h: No such file or directory
 #include "Freenove_WS2812_Lib_for_ESP32.h"
WHADDUP?!

**Comment by TinyuZhao** [comment]
> Hi! Trying the example in the readme gives me the following error:
> fatal error: Freenove_WS2812_Lib_for_ESP32.h: No such file or directory
> #include "Freenove_WS2812_Lib_for_ESP32.h"
> WHADDUP?!

Please start a new issue to ask a new question, with a specific compilation environment, and a specific example to use.
