### ISSUE TITLE
COM Port Output freezing

### ISSUE THREAD

**Issue by keithdennison** [m5stack/STAMP-C3#2]
The RGB_LED_Control program has an issue where the serial port output stops.  This is caused by setting pin 21 configuration wrong. It can be fixed by commenting it out on the list of pins that are being configured in the for loop that follows (in main.c):

```
#ifdef STAMP_C3
uint8_t PINS[] = {4, 5, 6, 7, 8, 10, 1, 0, /* 21, */ 20, 9, 18, 19, };
#define BTN_PIN 3
#endif

```

**Comment by PaulskPt** [comment]
Thank you! This worked also for me. I had also the problem that the monitor output stopped somewhere in line: ```I (317) gpio: GPIO[0] ...``` and next did not give output of actions in main when pressing the center button. Now it does!

**Comment by TinyuZhao** [comment]
Thank you for your help, I will fix him
