### ISSUE TITLE
Faulty examples

### ISSUE THREAD

**Issue by BadFlamingo666** [m5stack/STAMP-C3#5]
So, I was giving this repo a shot hoping to get my M5Stamp C3 running with Arduino IDE but to no avail. I followed the instructions in the readme but this is the error I get:
fatal error: Freenove_WS2812_Lib_for_ESP32.h: No such file or directory
 #include "Freenove_WS2812_Lib_for_ESP32.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: Freenove_WS2812_Lib_for_ESP32.h: No such file or directory

I would really like to get this thing running but all references online seems to be outdated. PLS HALP

**Comment by animevietsub** [comment]
Make sure you have installed `Freenove WS2812 Lib for ESP32` library.
Here is the library: [Freenove WS2812 Lib for ESP32](https://github.com/Freenove/Freenove_WS2812_Lib_for_ESP32)

**Comment by BadFlamingo666** [comment]
Ah, yes of course. I must have been tired and desperate 😆 
It works perfectly now. Big THANKS

**Comment by TinyuZhao** [comment]
Glad to see you've resolved the issue, have updated the example with a note.

Closed.
